# Source - https://stackoverflow.com/a
# Posted by JPG, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-22, License - CC BY-SA 4.0
services:

  redis:
    image: redis:latest
    container_name: rd01
    networks:
      - dokploy-network


  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: pg01
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../files/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
      - 5432
    networks:
      - dokploy-network

  webapp:
    build: .
    user: celeryuser
    volumes:
      - hf_models:/models/huggingface
      - docs:/backend/src/docs
    container_name: wa01
    command: /entrypoint.sh
    expose:
      - 8000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - dokploy-network


  celery:
    build: .
    user: celeryuser
    volumes:
      - hf_models:/models/huggingface
      - docs:/backend/src/docs
    container_name: cl01
    command: /celery_entrypoint.sh
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - dokploy-network

volumes:
  pgdata:
  hf_models:
  docs:

networks:
  dokploy-network:
    external: true